START TRANSACTION;
DROP INDEX "IX_IdentityResourceProperties_IdentityResourceId";

DROP INDEX "IX_IdentityResourceClaims_IdentityResourceId";

DROP INDEX "IX_ClientRedirectUris_ClientId";

DROP INDEX "IX_ClientPostLogoutRedirectUris_ClientId";

DROP INDEX "IX_ClientIdPRestrictions_ClientId";

DROP INDEX "IX_ClientGrantTypes_ClientId";

DROP INDEX "IX_ClientCorsOrigins_ClientId";

DROP INDEX "IX_ClientClaims_ClientId";

DROP INDEX "IX_ApiScopeProperties_ScopeId";

DROP INDEX "IX_ApiScopeClaims_ScopeId";

DROP INDEX "IX_ApiResourceScopes_ApiResourceId";

DROP INDEX "IX_ApiResourceProperties_ApiResourceId";

DROP INDEX "IX_ApiResourceClaims_ApiResourceId";

ALTER TABLE "Clients" ADD "CibaLifetime" integer;

ALTER TABLE "Clients" ADD "CoordinateLifetimeWithUserSession" boolean;

ALTER TABLE "Clients" ADD "DPoPClockSkew" interval NOT NULL DEFAULT INTERVAL '00:00:00';

ALTER TABLE "Clients" ADD "DPoPValidationMode" integer NOT NULL DEFAULT 0;

ALTER TABLE "Clients" ADD "InitiateLoginUri" text;

ALTER TABLE "Clients" ADD "PollingInterval" integer;

ALTER TABLE "Clients" ADD "PushedAuthorizationLifetime" integer;

ALTER TABLE "Clients" ADD "RequireDPoP" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Clients" ADD "RequirePushedAuthorization" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "ClientRedirectUris" ALTER COLUMN "RedirectUri" TYPE character varying(400);

ALTER TABLE "ClientPostLogoutRedirectUris" ALTER COLUMN "PostLogoutRedirectUri" TYPE character varying(400);

ALTER TABLE "ApiScopes" ADD "Created" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "ApiScopes" ADD "LastAccessed" timestamp with time zone;

ALTER TABLE "ApiScopes" ADD "NonEditable" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "ApiScopes" ADD "Updated" timestamp with time zone;

ALTER TABLE "ApiResources" ADD "RequireResourceIndicator" boolean NOT NULL DEFAULT FALSE;

CREATE TABLE "IdentityProviders" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Scheme" character varying(200) NOT NULL,
    "DisplayName" character varying(200),
    "Enabled" boolean NOT NULL,
    "Type" character varying(20) NOT NULL,
    "Properties" text,
    "Created" timestamp with time zone NOT NULL,
    "LastAccessed" timestamp with time zone,
    "NonEditable" boolean NOT NULL,
    "Updated" timestamp with time zone,
    CONSTRAINT "PK_IdentityProviders" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_IdentityResourceProperties_IdentityResourceId_Key" ON "IdentityResourceProperties" ("IdentityResourceId", "Key");

CREATE UNIQUE INDEX "IX_IdentityResourceClaims_IdentityResourceId_Type" ON "IdentityResourceClaims" ("IdentityResourceId", "Type");

CREATE UNIQUE INDEX "IX_ClientRedirectUris_ClientId_RedirectUri" ON "ClientRedirectUris" ("ClientId", "RedirectUri");

CREATE UNIQUE INDEX "IX_ClientPostLogoutRedirectUris_ClientId_PostLogoutRedirectUri" ON "ClientPostLogoutRedirectUris" ("ClientId", "PostLogoutRedirectUri");

CREATE UNIQUE INDEX "IX_ClientIdPRestrictions_ClientId_Provider" ON "ClientIdPRestrictions" ("ClientId", "Provider");

CREATE UNIQUE INDEX "IX_ClientGrantTypes_ClientId_GrantType" ON "ClientGrantTypes" ("ClientId", "GrantType");

CREATE UNIQUE INDEX "IX_ClientCorsOrigins_ClientId_Origin" ON "ClientCorsOrigins" ("ClientId", "Origin");

CREATE UNIQUE INDEX "IX_ClientClaims_ClientId_Type_Value" ON "ClientClaims" ("ClientId", "Type", "Value");

CREATE UNIQUE INDEX "IX_ApiScopeProperties_ScopeId_Key" ON "ApiScopeProperties" ("ScopeId", "Key");

CREATE UNIQUE INDEX "IX_ApiScopeClaims_ScopeId_Type" ON "ApiScopeClaims" ("ScopeId", "Type");

CREATE UNIQUE INDEX "IX_ApiResourceScopes_ApiResourceId_Scope" ON "ApiResourceScopes" ("ApiResourceId", "Scope");

CREATE UNIQUE INDEX "IX_ApiResourceProperties_ApiResourceId_Key" ON "ApiResourceProperties" ("ApiResourceId", "Key");

CREATE UNIQUE INDEX "IX_ApiResourceClaims_ApiResourceId_Type" ON "ApiResourceClaims" ("ApiResourceId", "Type");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260521085634_Configuration_to_OpenIdS', '10.0.7');

COMMIT;

