START TRANSACTION;
ALTER TABLE "PersistedGrants" DROP CONSTRAINT "PK_PersistedGrants";

ALTER TABLE "PersistedGrants" ALTER COLUMN "Key" DROP NOT NULL;

ALTER TABLE "PersistedGrants" ADD "Id" bigint GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE "PersistedGrants" ADD CONSTRAINT "PK_PersistedGrants" PRIMARY KEY ("Id");

CREATE TABLE "Keys" (
    "Id" text NOT NULL,
    "Version" integer NOT NULL,
    "Use" text,
    "DataProtected" boolean NOT NULL,
    "Algorithm" character varying(100) NOT NULL,
    "IsX509Certificate" boolean NOT NULL,
    "Data" text NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Keys" PRIMARY KEY ("Id")
);

CREATE TABLE "PushedAuthorizationRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReferenceHashValue" character varying(64) NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "Parameters" text NOT NULL,
    CONSTRAINT "PK_PushedAuthorizationRequests" PRIMARY KEY ("Id")
);

CREATE TABLE "ServerSideSessions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Key" character varying(100) NOT NULL,
    "Scheme" character varying(100) NOT NULL,
    "SubjectId" character varying(100) NOT NULL,
    "SessionId" character varying(100),
    "DisplayName" character varying(100),
    "Created" timestamp with time zone NOT NULL,
    "Renewed" timestamp with time zone NOT NULL,
    "Expires" timestamp with time zone,
    "Data" text NOT NULL,
    CONSTRAINT "PK_ServerSideSessions" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_PersistedGrants_ConsumedTime" ON "PersistedGrants" ("ConsumedTime");

CREATE UNIQUE INDEX "IX_PersistedGrants_Key" ON "PersistedGrants" ("Key");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260521085628_Grants_to_OpenIdS', '10.0.7');

COMMIT;

