[theme]
inherit = basic
stylesheet = css/site.min.css
pygments_style = none

[options]
analytics = true
gtm_key =
show_back_btn = true
back_btn_link =
back_btn_text =
show_version = true
version =
show_doc_bottom_nav_btns = true
show_sidebar_in_doc_navigation = true
custom_colour_mode = default
theme_header_texture = img/escheresque_ste.png
load_menu_expanded = false
error_404_email =
error_404_email_text =
error_404_string =
